#!/usr/bin/env python3
"""Regenerate reviewed operation metadata from immutable Elastic source commits.

No fetched source is executed. --check compares generated bytes without writing.
--cache keeps downloaded REST documents for offline/repeated generation.
"""
import argparse
import concurrent.futures
import hashlib
import json
from pathlib import Path
import urllib.request

PROFILES = {
    "8.19.21": "4fe44c255c3d0da06779b921e132cdc555ed9aff",
    "9.1.10": "f2e019bd8110088070638ca779ec1543188c0f43",
}
# Effect review is explicit. HTTP method alone does not decide the effect.
OPERATIONS = {
    "resolve": ("indices.resolve_index", "read", True),
    "mappings": ("indices.get_mapping", "read", True),
    "aliases": ("indices.get_alias", "read", True),
    "settings": ("indices.get_settings", "read", True),
    **{name: (name, "read", True) for name in (
        "search", "count", "msearch", "get", "mget", "termvectors",
        "mtermvectors", "search_template", "render_search_template", "get_script",
        "explain", "field_caps", "search_shards", "indices.validate_query",
    )},
    "msearch_template": ("msearch_template", "read", True),
    "eql.search": ("eql.search", "read", True),
    "esql.query": ("esql.query", "read", True),
    "cluster.state": ("cluster.state", "internal_proof", True),
    "enrich.get_policy": ("enrich.get_policy", "internal_proof", True),
    "sql.query": ("sql.query", "read", True),
    "sql.translate": ("sql.translate", "read", True),
    "sql.clear_cursor": ("sql.clear_cursor", "owned_context", True),
    **{name: (name, "owned_context", True) for name in (
        "open_point_in_time", "close_point_in_time", "scroll", "clear_scroll",
    )},
    **{name: (name, "mutation", False) for name in (
        "index", "update", "delete", "bulk", "update_by_query", "delete_by_query", "reindex",
        "indices.refresh", "indices.flush", "indices.forcemerge",
        "enrich.put_policy", "enrich.execute_policy", "enrich.delete_policy",
    )},
}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cache", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = Path(__file__).resolve().parents[2] / "internal/dialects/elasticsearch/operations.generated.json"
    args.cache.mkdir(parents=True, exist_ok=True)

    def load(item):
        version, commit, operation, api, effect, ready = item
        url = f"https://raw.githubusercontent.com/elastic/elasticsearch/{commit}/rest-api-spec/src/main/resources/rest-api-spec/api/{api}.json"
        path = args.cache / f"{commit}-{api}.json"
        if path.exists():
            raw = path.read_bytes()
        else:
            with urllib.request.urlopen(url, timeout=30) as response:
                raw = response.read(1 << 20)
            path.write_bytes(raw)
        spec = json.loads(raw)[api]
        return version, operation, {
            "api": api, "effect": effect, "implemented": ready,
            "source": url, "sha256": hashlib.sha256(raw).hexdigest(),
            "routes": [{"path": p["path"], "methods": p["methods"]} for p in spec["url"]["paths"]],
            "parameters": sorted(spec.get("params", {})),
        }

    work = [(version, commit, operation, *rule)
            for version, commit in PROFILES.items() for operation, rule in OPERATIONS.items()]
    result = {version: {} for version in PROFILES}
    with concurrent.futures.ThreadPoolExecutor(max_workers=6) as pool:
        for version, operation, data in pool.map(load, work):
            result[version][operation] = data
    encoded = (json.dumps(result, indent=2, sort_keys=True) + "\n").encode()
    if args.check:
        if output.read_bytes() != encoded:
            raise SystemExit("operation catalog differs from pinned REST inputs")
    else:
        output.write_bytes(encoded)


if __name__ == "__main__":
    main()
